# Generated by Django 3.0.5 on 2020-05-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroEducativo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=14, unique=True)),
                ('nombre', models.CharField(max_length=256)),
                ('en_funcionamiento', models.IntegerField()),
            ],
            options={
                'db_table': 'secretaria_centroeducativo',
                'ordering': ('codigo', 'nombre'),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=2, unique=True)),
                ('nombre', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'secretaria_departamento',
                'ordering': ('codigo', 'nombre'),
                'managed': False,
            },
        ),
    ]
