# Generated by Django 3.0.5 on 2020-05-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=2, unique=True)),
                ('nombre', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'secretaria_municipio',
                'ordering': ('codigo', 'nombre'),
                'managed': False,
            },
        ),
    ]
