# Generated by Django 3.0.5 on 2020-06-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alumno_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='contacto',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='persona',
            name='genero',
            field=models.CharField(choices=[('M', 1), ('F', 2)], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
