# Generated by Django 3.0.5 on 2020-06-24 18:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200624_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefonos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), default=list, null=True, size=None),
        ),
    ]
