# Generated by Django 3.0.5 on 2020-06-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200624_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='telefonos',
        ),
        migrations.AddField(
            model_name='persona',
            name='telefono',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
