# Generated by Django 3.0.5 on 2020-05-25 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majad', '0004_auto_20200525_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroReferencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sede', models.IntegerField()),
                ('nombre', models.CharField(max_length=256)),
                ('municipio', models.IntegerField()),
                ('direccion', models.TextField()),
                ('coordinador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='majad.Coordinador')),
            ],
            options={
                'ordering': ('nombre', 'municipio'),
            },
        ),
    ]
