# Generated by Django 3.0.5 on 2020-05-25 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majad', '0007_mallacurricular'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mallacurricular',
            options={'ordering': ('codigo',)},
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, unique=True)),
                ('malla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='majad.MallaCurricular')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
    ]
