# Generated by Django 3.0.5 on 2020-05-27 16:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majad', '0011_auto_20200527_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinador',
            name='departamento',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
            preserve_default=False,
        ),
    ]
