# Generated by Django 3.0.5 on 2020-06-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majad', '0014_auto_20200602_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='codigo',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
