# Generated by Django 3.0.5 on 2020-06-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majad', '0015_auto_20200602_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grado',
            name='nombre',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='mallacurricular',
            name='codigo',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
