# Generated by Django 3.0.5 on 2020-06-02 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majad', '0016_auto_20200602_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrador',
            old_name='departamento',
            new_name='departamentos',
        ),
        migrations.RenameField(
            model_name='coordinador',
            old_name='departamento',
            new_name='departamentos',
        ),
    ]
