# Generated by Django 3.0.5 on 2020-06-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majad', '0017_auto_20200602_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, unique=True)),
                ('inicio', models.DateField()),
                ('final', models.DateField()),
            ],
            options={
                'ordering': ('inicio',),
            },
        ),
    ]
