# Generated by Django 3.0.5 on 2020-06-11 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majad', '0018_periodo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grado',
            options={'ordering': ('-id',)},
        ),
    ]
