# Generated by Django 3.0.5 on 2020-08-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majad', '0019_auto_20200611_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinador',
            name='centro_referencia',
        ),
        migrations.AddField(
            model_name='coordinador',
            name='centro_referencia',
            field=models.ManyToManyField(to='majad.CentroReferencia'),
        ),
    ]
