# Generated by Django 3.0.5 on 2020-08-18 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majad', '0020_auto_20200814_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinador',
            name='departamentos',
        ),
    ]
