# Generated by Django 3.0.5 on 2020-08-22 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200625_1758'),
        ('majad', '0021_remove_coordinador_departamentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Alumno')),
                ('centro_referencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='majad.CentroReferencia')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='majad.Grado')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='majad.Periodo')),
            ],
            options={
                'ordering': ('-periodo', 'centro_referencia', 'grado'),
            },
        ),
    ]
