# Generated by Django 3.0.5 on 2020-08-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majad', '0022_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='horas',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
